#!/usr/bin/env bash
# Configuring subdomain zones
# shellcheck disable=SC2027
# shellcheck disable=SC2086

display_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type="$3"
    local destination="$4"
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Function to query DNS records for a domain and subdomain
query_dns() {
    local domain="$1"
    local subdomain="$2"
    dig_output=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ { getline; print }')
    if [[ -n "$dig_output" ]]; then
        record_type=$(echo "$dig_output" | awk '{print $4}')
        destination=$(echo "$dig_output" | awk '{print $5}')
        display_subdomain_info "$domain" "$subdomain" "$record_type" "$destination"
    fi
}

# Main script
domain="$1"
subdomain="$2"

if [[ -z "$subdomain" ]]; then
    query_dns "$domain" "www"
    query_dns "$domain" "lb-01"
    query_dns "$domain" "web-01"
    query_dns "$domain" "web-02"
else
    query_dns "$domain" "$subdomain"
fi
