#!/usr/bin/env bash
# script that transfers a file from our client to a server

file_to_transfer=$1
to_ip=$2
username=$3
private_key=$4

if [[ -z "$private_key" ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$private_key" "$file_to_transfer" "$username@$to_ip:"
fi
