#!/usr/bin/env bash
# install nginx on ubuntu machine

#!/bin/bash

# Install nginx with the -y option
apt-get update
apt-get install -y nginx

echo "Hello World!" > /usr/share/nginx/html/index.html

service nginx restart > /dev/null 2>&1
