#!/usr/bin/env bash
# configure nginx with custom headers
# shellcheck disable=SC2059

sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html/
echo 'Hello World!' > /var/www/html/index.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/

hostname=$(hostname)
custom_header="add_header X-Served-By $hostname;"
sudo sed -i "/server_name _;/a \\\t$custom_header" /etc/nginx/sites-available/default
sudo systemctl reload nginx
