#!/usr/bin/env bash
# configure nginx with custom headers
# shellcheck disable=SC2059

function install_and_configure_nginx(){
	sudo apt-get update
    	sudo apt-get -y install nginx
    	sudo chown -R "$USER":"$USER" /var/www/html/
    	echo 'Hello World!' > /var/www/html/index.html
    	sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
    	redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
    	sudo sed -i "26i $redirect" /etc/nginx/sites-available/default
	
	server_config="server {
		add_header X-Served-By \$hostname;	
	}"	

	echo -e "$server_config" >> /etc/nginx/sites-available/default

    	if [[ $(pgrep nginx) ]]; then
        	sudo nginx -s reload
    	else
        	sudo service nginx start
    	fi
}
install_and_configure_nginx;
