#!/usr/bin/env bash
# Script to install and configure HAproxy loadbalancer on the server(lb-01)

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
defaults
    mode http
    balance roundrobin

frontend web-frontend
    bind *:80
    default_backend web-backend

backend web-backend
    server STUDENT_ID-web-01 54.237.83.201:80 check
    server STUDENT_ID-web-02 54.236.54.165:80 check
EOF

sudo systemctl enable haproxy
sudo service haproxy start
