#!/usr/bin/env bash
# Script to install and configure HAproxy loadbalancer on the server(lb-01)
# shellcheck disable=SC2059

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*

lb_config=\
"defaults
    mode http

frontend web-frontend
    bind *:80
    default_backend web-backend

backend web-backend
    balance roundrobin
    server STUDENT_ID-web-01 54.237.83.201:80 check
    server STUDENT_ID-web-02 54.236.54.165:80 check
"

echo -e "$lb_config" > /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

if [[ "$(pgrep -f haproxy)" ]]; then
    sudo service haproxy restart
else
    sudo service haproxy start
fi
