#!/bin/bash
git add .

echo "Insert COMMIT comment"
IFS= read -r commitVar

git commit -m "$commitVar"

# Set the credentials globally
git config --global credential.helper store
git config --global user.name minanadynarouz
git config --global user.token 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

# Push the changes
git push
