#!/bin/bash
git add .

echo "Insert COMMIT comment"
IFS= read -r commitVar

git commit -m "$commitVar"

echo "Insert Git Username:"
IFS= read -r username

echo "Insert Git Password:"
IFS= read -r -s password

# Set the credentials globally
git config --global credential.helper store
git config --global user.name "$username"
git config --global user.password "$password"

# Push the changes
git push
