#!/usr/bin/env bash
# creates file and display text

deleteScript(){
	rm /var/run/myscript.pid
	exit
}

trap "echo I hate the kill command;deleteScript" 15
trap "echo Y U no love me?!" 2

echo $$ >> /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
done
