#!/usr/bin/env bash
#init script for `manage_my_process` process

#!/usr/bin/env bash
# script that controls manage_my_process script

arg=$1

pid_file="/var/run/my_process.pid"

if [ "$#" -ne 1 ] || { [ "$arg" != "start" ] && [ "$arg" != "restart" ] && [ "$arg" != "stop" ]; }; then
    echo "Usage: manage_my_process {start|stop|restart}"
elif [ "$arg" == "start" ]; then
	./manage_my_process &
	pid=$!
	echo "$pid" > "$pid_file"
	echo "manage_my_process started"
elif [ "$arg" == "stop" ]; then
    	pid=$(cat "$pid_file")
	kill -9 "$pid"
	rm -f "$pid_file"
	echo "manage_my_process stopped"
elif [ "$arg" == "restart" ]; then
	if [ -e $pid_file ]; then
		pid=$(cat "$pid_file")
        	kill -9 "$pid"
        	rm -f "$pid_file"
	fi
	./manage_my_process &
	pid=$!
	echo "$pid" > "$pid_file"
	echo "manage_my_process restarted"
fi
